"""empty message

Revision ID: 290c7c6ca877
Revises: 82cbb8689075
Create Date: 2022-06-01 14:38:24.499120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290c7c6ca877'
down_revision = '82cbb8689075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
