"""empty message

Revision ID: 32378d741f52
Revises: e1fd7dff07c2
Create Date: 2022-06-01 10:44:33.107753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32378d741f52'
down_revision = 'e1fd7dff07c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.JSON(), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
