"""empty message

Revision ID: 89aba793eecd
Revises: 290c7c6ca877
Create Date: 2022-06-01 14:39:32.424739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89aba793eecd'
down_revision = '290c7c6ca877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#    op.drop_column('Artist', 'seeking_venue')
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.execute('UPDATE "Venue" SET seeking_talent = False WHERE seeking_talent IS NULL;')
    op.alter_column('Venue','seeking_talent', nullable=False)

   # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    op.add_column('Artist', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.execute('UPDATE "Artist" SET seeking_venue = False WHERE seeking_venue IS NULL;')
    op.alter_column('Artist','seeking_venue', nullable=False)

    # ### end Alembic commands ###
