"""empty message

Revision ID: c00d1a76edb2
Revises: c269129a0241
Create Date: 2022-05-31 20:57:23.894354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00d1a76edb2'
down_revision = 'c269129a0241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows')
    # ### end Alembic commands ###
